<?xml version='1.0'?>
<robot name="robot_ipsa" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find in426_desc)/xacro/material.xacro"/>
    <xacro:include filename="$(find in426_desc)/xacro/Robot_1/robot_1_ros2_control.xacro"/>
    <xacro:include filename="$(find in426_desc)/xacro/Robot_1/robot_1.gazebo"/>

    <!-- VARIABLES -->
    <xacro:property name="base_radius" value="0.25"/>
    <xacro:property name="base_length" value="0.03"/> <!-- Kept as per original -->

    <xacro:property name="link_1_length" value="0.4"/> <!-- Kept as per original -->
    <xacro:property name="link_1_radius" value="0.08"/>

    <xacro:property name="link_2_length" value="0.3"/> <!-- Kept as per original -->
    <xacro:property name="link_2_radius" value="0.05"/>

    <xacro:property name="link_3_length" value="0.2"/> <!-- Kept as per original -->
    <xacro:property name="link_3_radius" value="0.03"/>

    <xacro:property name="link_4_length" value="0.025"/> <!-- Kept as per original -->
    <xacro:property name="link_4_radius" value="0.015"/>

    <!-- MACROS -->
    <xacro:macro name="cylinder_inertial" params="mass radius length o_xyz o_rpy">
        <inertial>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <mass value="${mass}"/>
            <inertia ixx="${mass*(3*radius*radius+length*length)/12}" ixy="0.0" ixz="0.0"
                     iyy="${mass*(3*radius*radius+length*length)/12}" iyz="0.0" izz="${mass*radius*radius/2}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertial" params="mass radius o_xyz o_rpy">
        <inertial>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <mass value="${mass}"/>
            <inertia ixx="${2*mass*radius*radius/5}" ixy="0.0" ixz="0.0"
                     iyy="${2*mass*radius*radius/5}" iyz="0.0" izz="${2*mass*radius*radius/5}"/>
        </inertial>
    </xacro:macro>

    <!-- *****World link (no visual geometry)***** -->
    <link name="world"/>

    <!-- *****Base link***** -->
    <joint name="world_to_base" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 0.4" rpy="0 0 0"/> <!-- Offset z by 0.4 to match L1 = 0.43 (0.4 + 0.03 = 0.43) -->
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
            <material name="base_material">
                <color rgba="0 0 0 1"/> <!-- Black, fully opaque -->
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="1" radius="${base_radius}" length="${base_length}" o_xyz="0 0 ${base_length/2}" o_rpy="0 0 0"/>
    </link>

    <!-- *****LINK 1***** -->
    <link name="link_1">
        <visual>
            <origin xyz="0 0 ${link_1_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_1_radius}" length="${link_1_length}"/>
            </geometry>
            <material name="link_1_material">
                <color rgba="1 0 0 0.5"/> <!-- Red, 50% transparency -->
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${link_1_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${link_1_radius}" length="${link_1_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="1" radius="${link_1_radius}" length="${link_1_length}" o_xyz="0 0 ${link_1_length/2}" o_rpy="0 0 0"/>
    </link>

    <joint name="base_to_1" type="revolute">
        <parent link="base_link"/>
        <child link="link_1"/>
        <origin xyz="0 0 ${base_length}" rpy="0 0 0"/> <!-- On top of base -->
        <axis xyz="0 0 1"/> <!-- Rotate around z-axis (theta1) -->
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="1" effort="100"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- *****LINK 2p (Joint Sphere)***** -->
    <link name="link_2p">
        <visual>
            <geometry>
                <sphere radius="0.09"/>
            </geometry>
            <material name="link_2p_material">
                <color rgba="1 0.5 0 0.5"/> <!-- Orange, 50% transparency -->
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.09"/>
            </geometry>
        </collision>
        <xacro:sphere_inertial mass="0.1" radius="0.09" o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <joint name="1_to_2p" type="fixed">
        <parent link="link_1"/>
        <child link="link_2p"/>
        <origin xyz="0 0 ${link_1_length}" rpy="0 0 0"/> <!-- At end of link_1 -->
    </joint>

    <!-- *****LINK 2***** -->
    <link name="link_2">
        <visual>
            <origin xyz="${0.228*link_2_length/0.3} 0 0" rpy="0 0 ${pi/2}"/> <!-- Scale to match x-contribution -->
            <geometry>
                <cylinder radius="${link_2_radius}" length="${link_2_length}"/>
            </geometry>
            <material name="link_2_material">
                <color rgba="1 0.5 0 0.5"/> <!-- Orange, 50% transparency -->
            </material>
        </visual>
        <collision>
            <origin xyz="${0.228*link_2_length/0.3} 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <cylinder radius="${link_2_radius}" length="${link_2_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="1" radius="${link_2_radius}" length="${link_2_length}" o_xyz="${0.228*link_2_length/0.3} 0 0" o_rpy="0 0 ${pi/2}"/>
    </link>

    <joint name="1_to_2" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="0 0 ${link_1_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/> <!-- Rotate around y-axis (theta2) -->
        <limit lower="-0.52" upper="${pi/2}" velocity="1" effort="100"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- *****LINK 3p (Joint Sphere)***** -->
    <link name="link_3p">
        <visual>
            <geometry>
                <sphere radius="0.06"/>
            </geometry>
            <material name="link_3p_material">
                <color rgba="0 1 0 0.5"/> <!-- Green, 50% transparency -->
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.06"/>
            </geometry>
        </collision>
        <xacro:sphere_inertial mass="0.1" radius="0.06" o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <joint name="2_to_3p" type="fixed">
        <parent link="link_2"/>
        <child link="link_3p"/>
        <origin xyz="${0.228} 0 0" rpy="0 0 0"/> <!-- Match effective length -->
    </joint>

    <!-- *****LINK 3***** -->
    <link name="link_3">
        <visual>
            <origin xyz="${0.072*link_3_length/0.2} 0 0" rpy="0 0 ${pi/2}"/> <!-- Scale to match x-contribution -->
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}"/>
            </geometry>
            <material name="link_3_material">
                <color rgba="0 1 0 0.5"/> <!-- Green, 50% transparency -->
            </material>
        </visual>
        <collision>
            <origin xyz="${0.072*link_3_length/0.2} 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="1" radius="${link_3_radius}" length="${link_3_length}" o_xyz="${0.072*link_3_length/0.2} 0 0" o_rpy="0 0 ${pi/2}"/>
    </link>

    <joint name="2_to_3" type="revolute">
        <parent link="link_2"/>
        <child link="link_3"/>
        <origin xyz="${0.228} 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/> <!-- Rotate around x-axis (theta3) -->
        <limit lower="${-pi/2}" upper="0" velocity="1" effort="100"/>
        <dynamics damping="0.7"/>
    </joint>

    <!-- *****LINK 4***** -->
    <link name="link_4">
        <visual>
            <origin xyz="${0.025*link_4_length/0.025} 0 0" rpy="0 0 ${pi/2}"/> <!-- Scale to match x-contribution -->
            <geometry>
                <cylinder radius="${link_4_radius}" length="${link_4_length}"/>
            </geometry>
            <material name="link_4_material">
                <color rgba="0 0 1 0.5"/> <!-- Blue, 50% transparency -->
            </material>
        </visual>
        <collision>
            <origin xyz="${0.025*link_4_length/0.025} 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <cylinder radius="${link_4_radius}" length="${link_4_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial mass="1" radius="${link_4_radius}" length="${link_4_length}" o_xyz="${0.025*link_4_length/0.025} 0 0" o_rpy="0 0 ${pi/2}"/>
    </link>

    <joint name="3_to_4" type="fixed">
        <parent link="link_3"/>
        <child link="link_4"/>
        <origin xyz="${0.072} 0 0" rpy="0 0 0"/>
    </joint>
</robot>